# site settings
title: liyb
subtitle: A simple program developer
email: liyb@aliyun.com
description: We are committed to developing innovative and practical applications designed to provide a more efficient, convenient and interesting digital experience for all kinds of users. Whether you are looking for tools to improve work efficiency or applications that add more fun to your life, we can provide you with the right choice.
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 1234 Somewhere Road
city: Beijing
state: Beijing
zip_code: 100000
country: China
phone: (716) 555-5555

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/liyab93
  GitLab:
  Google-Plus:
  Instagram:
  LinkedIn:
  Twitter:
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
