# site settings
title: liyb
email: liyb@aliyun.com
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: liyb

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6
# 禁止加载到首页的文件夹
tiles-exclude-folders:
  - _policys
  - _guides

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/liyab93
  GitLab:
  Google-Plus:
  Instagram:
  LinkedIn:
  Twitter:
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

# 忽略的文档
exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 

# 参与编译的文件夹
include:
  - _policys
  - _guides
  - _home

# 多语言
i18n:
  cn:
    menu: "菜单"
    title: "标题"
    email: "邮箱"
    content: "内容"
    send: "发送"
    clear: "清空"
    getStarted: "开始使用"
    subtitle: "用代码，创造无限可能"
    description: "欢迎来到我的 App 世界！这里记录着我的开发历程，分享着我的作品，也期待着与你交流。希望你能在这里发现有趣的 App，感受科技的魅力！"
    copyright: "版权所有 ©2024 liyb，保留所有权利。"
  en:
    menu: "Menu"
    title: "Title"
    email: "Email"
    content: "Message"
    send: "Send"
    clear: "Clear"
    getStarted: "Get Started"
    subtitle: "Use code, create unlimited possibilities"
    description: "Welcome to my App world! Here, I record my development journey, share my works, and also expect to connect with you. I hope you can find interesting Apps here, and feel the charm of technology!"
    copyright: "Copyright ©2024 liyb, All right reserved."
  ct:
    menu: "菜單"
    title: "標題"
    email: "郵箱"
    content: "內容"
    send: "發送"
    clear: "清除"
    getStarted: "開始使用"
    subtitle: "用代碼，創造無限可能"
    description: "歡迎來到我的 App 世界！這裏記錄著我的開發歷程，分享著我的作品，也期待著與你交流。希望你能在這裏找到有趣的 App，感受科技的魅力！"
    copyright: "版權所有 ©2024 liyb，保留所有權利。"